### ISSUE TITLE
Compatibility?

### ISSUE THREAD

**Issue by langjy** [jeneser/vue-scroll-behavior#10]
兼容性问题

由于使用的一些es6方法到时低版本安卓机无法显示，如数组的 find 和 findIndex 方法

**Comment by jeneser** [comment]
这个问题开发的时候没过多考虑，vue.js本身就是比较前卫的，兼容性可以采用Polyfill来解决。当然如果换用兼容性较好的函数势必会增加代码量。如果你有好的想法或是能帮助改进此项目，我将会非常欢迎。

**Comment by jeneser** [comment]
Compatibility issues need to be discussed. Like some functions: `find`  `findIndex`.

**Comment by jeneser** [comment]
Move to https://github.com/jeneser/vue-scroll-behavior/issues/11
