### ISSUE TITLE
Uncaught TypeError: Cannot read property 'maxLength' of undefined

### ISSUE THREAD

**Issue by kfeng0806** [jeneser/vue-scroll-behavior#17]
vue: ^2.5
vue-router: ^3.0.2

引入后出现如下错误
`Uncaught TypeError: Cannot read property 'maxLength' of undefined`

![](https://i.imgur.com/5H9lhdW.jpg)

**Comment by kfeng0806** [comment]
#18

**Comment by jeneser** [comment]
done
