### ISSUE TITLE
Github 上的 readme 与 npm 上的对不上

### ISSUE THREAD

**Issue by Watanuki-Kimihiro** [jeneser/vue-scroll-behavior#22]
Github 上的 readme 与 npm 上的对不上，通过 npm install 安装的 0.2.0 版本无法使用 “自定义滚动容器” 的选项。
Fork 下来，发现自定义滚动容器的功能添加于 0.2.0 版本发布之后，这个新功能很实用，希望作者有时间能在 npm 同步更新一下版本。

**Comment by jeneser** [comment]
已发布 v0.3.0。Thank you!
