### ISSUE TITLE
不能记录滚动条位置

### ISSUE THREAD

**Issue by moshanghan** [jeneser/vue-scroll-behavior#6]
看了下demo，ajax请求数据放在了vuex中，
说下我遇到的问题
ajax没有写在vuex中，是在mounted()中，列表去详情，依然执行mounted 中的ajax方法，不能记录位置

**Comment by jeneser** [comment]
感谢您提交issue给我！
首先，`vue-scroll-behavior
`的设计初衷是:以最简单的使用方式来统一解决页面滚动位置的记录与恢复。目前的核心代码不足一百行，其核心功能是完全依赖`vue-router`的导航钩子的。现在的版本还在开发版，是存在不完善的地方的，并且现在的版本，记录和恢复位置信息是在路由离开之前(`afterEach`)和进入之前(`beforeEach()`)执行的，如果数据因为种种原因延迟，该插件都是无能为力的。参考:https://github.com/jeneser/vue-scroll-behavior/issues/2。根据你提供的信息，初步判断为数据延迟导致的。
> 对于数据延迟的问题，滚动时机的控制特性将会被加入到该插件，可以在这里进行讨论https://github.com/jeneser/vue-scroll-behavior/issues/3 

您能提供更多的信息或相关代码来帮助我改进此插件吗?
