### ISSUE TITLE
Regexp does not work

### ISSUE THREAD

**Issue by lokkomokko** [jeneser/vue-scroll-behavior#7]
I have route /website, in script write -  
Vue.use(vueScrollBehavior, {
  router: router,
  maxLength: 100,
  ignore: [/\/website/, /\/zoo/],
})

but it ignore my ignore, what Im doing wrong?

**Comment by lokkomokko** [comment]
`ignore: [/\/website/, /\/zoo/],`

**Comment by jeneser** [comment]
Have you solved it yet?
If you write like this: `ignore: [/\/website/, /\/zoo/],` it works well.
But, I don't rule out other factors. If you find these issues, please tell me and provide more relevant code. I'd be happy to make a change for it. I'd be happy to accept PR, too.
Thank you very much.

**Comment by lokkomokko** [comment]
very strange, I solved this problem to manualy write in route js scroll behaviour that look at meta of components and if need scrolled it top, anyway thank you too! very good plugin

**Comment by jeneser** [comment]
Yep, happy coding.

**Comment by c-baeumer** [comment]
This is an old issue, but I´m struggling with the same problem.

I think the Problem is, that `isIgnoreRoute` is not returning any value:

```
/**
 * Is ignore route
 */
export function isIgnoreRoute (target) {
  vueScrollBehavior._ignore.some(e => {
    return target.fullPath.match(e)
  })
}
```

It worked for me, when I change it to:

```
/**
 * Is ignore route
 */
export function isIgnoreRoute (target) {
  return vueScrollBehavior._ignore.some(e => {
    return target.fullPath.match(e)
  })
}
```
