### ISSUE TITLE
Feature: Add simple customisable delay

### ISSUE THREAD

**Issue by decates** [jeneser/vue-scroll-behavior#8]
I use transitions with the router, and currently the scroll happens immediately, while the views are in transition.

Add a simple delay option, specified in milliseconds and defaulting to 0, allowing consumers to delay the scroll. This will allow those who use, for example, a standard out-in fade transition for all of their route changes to use this library.

I can contribute the changes for this feature if accepted.

**Comment by jeneser** [comment]
That looks nice. We really need a simple delay option. But, I didn't finish it. I will be very excited if you can contribute the changes for this feature.

**Comment by jeneser** [comment]
@decates 
Thank you very much. I will close this issue.
